### ISSUE TITLE
Maven repository down?

### ISSUE THREAD

**Issue by CDFN** [Ivan1pl/witchcraft#10]
Hey,
Is maven repository down? Sadly it doesn't load for me.

**Comment by Ivan1pl** [comment]
Hey,

Thank you for your report. I have taken down my nexus repository because it costs too much to maintain a private nexus server. I will try to release this to a public maven repository like jcenter or sonatype OSS.

For now, to use this, you can include this in your local maven repository. Simply clone the git repository (`git clone https://github.com/Ivan1pl/witchcraft.git`), go to the directory you cloned into and run this command:
```
gradlew clean publishToMavenLocal
```

**Comment by Ivan1pl** [comment]
Witchcraft is now available on bintray. New repository URL: `https://dl.bintray.com/ivan1pl/ivan1pl-bukkit`
